### ISSUE TITLE
Nginx 1.7.10 support

### ISSUE THREAD

**Issue by neilstuartcraig** [cep21/healthcheck_nginx_upstreams#21]
Hi

I'm trying to use this module on Nginx 1.7.10 and getting compile-time errors (sorry, I didn't capture them stupidly) - I just wondered if you have any plans to support 1.7.10 (it looked to me like some nginx functionality had changed and broken compatibilty).

I've compiled in other modules successfully BTW.

Cheers
Neil

**Comment by cep21** [comment]
Hi,

I havn't had time to update this plugin in a long time.  There is better support at https://github.com/yaoweibin/nginx_upstream_check_module, which may do what you want.

**Comment by neilstuartcraig** [comment]
Hi Jack

Thanks for the reply. I did find that module actually but thanks for the suggestion - it’s working well.

Cheers
