### ISSUE TITLE
Patch can not be installed！

### ISSUE THREAD

**Issue by qwe109** [cep21/healthcheck_nginx_upstreams#22]
Hello, I want to install this module, but the patch can not be installed, can not continue down, I hope you can help me, thank you!
Here's my console info and environment:
centos7
nginx1.8

# patch –p1< ../cep21-healthcheck_nginx_upstreams-b33a846/nginx.patch 
patching file –p1
Hunk #1 FAILED at 4267.
1 out of 1 hunk FAILED -- saving rejects to file –p1.rej
patching file –p1
Hunk #1 FAILED at 106.
1 out of 1 hunk FAILED -- saving rejects to file –p1.rej
patching file –p1
Hunk #1 FAILED at 4.
Hunk #2 FAILED at 12.
Hunk #3 FAILED at 23.
Hunk #4 FAILED at 57.
Hunk #5 FAILED at 365.
Hunk #6 FAILED at 410.
Hunk #7 FAILED at 471.
Hunk #8 FAILED at 576.
Hunk #9 FAILED at 601.
Hunk #10 FAILED at 617.
10 out of 10 hunks FAILED -- saving rejects to file –p1.rej
patching file –p1
Hunk #1 FAILED at 26.
1 out of 1 hunk FAILED -- saving rejects to file –p1.rej

**Comment by cep21** [comment]
Hi,

I haven't been able to keep up with this module.  I recommend using https://github.com/yaoweibin/nginx_upstream_check_module

**Comment by qwe109** [comment]
@cep21 thanks a lot !
